#!/bin/sh
# Build the wasm QR decoder and install it into the sendmecongo-mp miniprogram.
#
#   tools/build-decoder-wasm.sh
#
# 1. compiles crates/sendmecongo-decoder-wasm for wasm32-unknown-unknown
#    (profile `wasm-release`, defined at the workspace root)
# 2. base64-embeds the .wasm into sendmecongo-mp/workers/decoder/wasm-data.js
#
# The miniprogram worker has no filesystem/wasm-bindgen glue, so the module
# ships as base64 and is decoded by workers/decoder/b64.js at startup.
set -eu
cd "$(dirname "$0")/.."

TARGET_DIR=target/wasm32-unknown-unknown/wasm-release
OUT_JS=../sendmecongo-mp/workers/decoder/wasm-data.js

cargo build -p sendmecongo-decoder-wasm --target wasm32-unknown-unknown --profile wasm-release

{
  printf '// AUTO-GENERATED by tools/build-decoder-wasm.sh — do not edit.\n'
  printf '// base64 of sendmecongo_decoder_wasm.wasm (rxing, wasm-release profile).\n'
  printf "module.exports = '"
  base64 -i "$TARGET_DIR/sendmecongo_decoder_wasm.wasm" | tr -d '\n'
  printf "';\n"
} > "$OUT_JS"

echo "wrote $OUT_JS ($(wc -c < "$OUT_JS" | tr -d ' ') bytes)"
